FROM mysql:5.6
  		  
ADD database.sql /docker-entrypoint-initdb.d

# build: docker build -f Dockerfile.db -t db_gdc .
# run:   docker run -e MYSQL_ROOT_PASSWORD=qtc MYSQL_DATABASE=mydb_gdo -p 3306:3306 db_gdc 
