version: '3'

services:
  db:
    build:
      dockerfile: Dockerfile.db
      context: .
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: pepe
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "somewordpress"
    ports:
      - "2051:80"
  web:
    depends_on:
      - db
    links:
      - db:db
    build: .
    volumes:
      - ".:/src"
    ports:
      - "3030:2050"
    restart: always
  gulp:
    depends_on:
      - web
    links:
      - web:web
    volumes:
      - ".:/src"
    build:
      dockerfile: DockerfileGulp
      context: .
    restart: always
